version: "2"
services:
  php:
    image: circlical/php74app-behat:latest
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/php.ini:delegated
      - ./docker/php-fpm.conf:/usr/local/etc/php-fpm.conf:delegated
      - ./docker/php-log/:/var/log/php/:delegated
      - nfsmount:/code:cached
    networks:
      - sample-testnet

  web:
    image: nginx:latest
    ports:
      - "42800:80"
    depends_on:
      - php
    volumes:
      - ./docker/site.conf:/etc/nginx/conf.d/site.conf:delegated
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:delegated
      - ./docker/nginx-log:/var/log/nginx/:delegated
      - nfsmount:/code:cached
    links:
      - php
    networks:
      - sample-testnet

  chrome:
    image: selenium/standalone-chrome:4.2
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
      - SE_SCREEN_DEPTH=24
      - SE_SCREEN_DPI=96
    networks:
      - sample-testnet

networks:
  sample-testnet:
    driver_opts:
      com.docker.network.driver.mtu: 1500
    driver: bridge

volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}"